### ISSUE TITLE
无法创建配置

### ISSUE THREAD

**Issue by seepine** [azicen/docker-clash-verge-rev#1]
![image](https://github.com/user-attachments/assets/c41d288b-f67f-4add-b53e-092033e45e99)

挂载的volume设置了777也是这个错误

**Comment by azicen** [comment]
设置 `PUID` 和 `PGID` 两个环境变量，参考这个文档：[docs](https://docs.linuxserver.io/general/understanding-puid-and-pgid/)

**Comment by azicen** [comment]
> @azicen 你好又遇到了个问题，导入订阅后，显示成功，编辑文件也能看到节点信息，但是代理页面没有显示出节点，还是默认的 ![image](https://private-user-images.githubusercontent.com/93666053/396900178-9668ebac-4ae1-4456-b6e5-562f283c890c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ1MjM5NjUsIm5iZiI6MTczNDUyMzY2NSwicGF0aCI6Ii85MzY2NjA1My8zOTY5MDAxNzgtOTY2OGViYWMtNGFlMS00NDU2LWI2ZTUtNTYyZjI4M2M4OTBjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE4VDEyMDc0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJjNjcwZWI2MTI3ZmVkZjNiOTI4ZDU3MGI4YjZjOGE0M2FiZmM1ODFjN2Y0ODMzMjhiMWU1MTg5NjY1MTFiNTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.dz6polvTSXdIYwgb0Lec4Oj6Fo7ZV9tY_mCuDgar9ag)

本地客户端中尝试是否可用呢？


> 编辑之后保存报错，不知道是否有关联
> 
> ![image](https://private-user-images.githubusercontent.com/93666053/396900937-097a5dc1-9233-4c25-86b6-ecd499ce09c0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ1MjM5NjUsIm5iZiI6MTczNDUyMzY2NSwicGF0aCI6Ii85MzY2NjA1My8zOTY5MDA5MzctMDk3YTVkYzEtOTIzMy00YzI1LTg2YjYtZWNkNDk5Y2UwOWMwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE4VDEyMDc0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg3YzBlYzc5ZWFlOWJiMzhlNTM1MmMxOGY5YTM1OGM1N2ZkMTA0NDU5Yjk2NDFlZmEyOGViZDQyNDkyMzQ3ZjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.9CjNR2_D8Wtm5d4y94odO9k_RbaB-38Af2sgWBX8jLg)

这个问题是怎么触发的？

这是导入url配置出现的错误吗？可能是网络没法直接访问输入的url。

**Comment by azicen** [comment]
本地客户端尝试一下是否有相同的问题呢，我按照你说的尝试没有触发这个错误

**Comment by azicen** [comment]
> 日志内容，有个error
> 
> ```
> 2024-12-18 20:48:53 ERROR - No such file or directory (os error 2)
> 2024-12-18 20:48:53 INFO - try to run core in service mode
> 2024-12-18 20:48:53 INFO - start service: {"bin_path": "/usr/bin/verge-mihomo", "config_dir": "/config/.local/share/io.github.clash-verge-rev.clash-verge-rev", "core_type": "verge-mihomo", "config_file": "/config/.local/share/io.github.clash-verge-rev.clash-verge-rev/clash-verge.yaml", "log_file": "/config/.local/share/io.github.clash-verge-rev.clash-verge-rev/logs/service/2024-12-18-2048.log"}
> 2024-12-18 20:48:53 INFO - window state restored successfully
> 2024-12-18 20:48:53 ERROR - No such file or directory (os error 2)
> ```

这段日志里的文件应该都存在，你可以验证一下。

删除所有logs下的文件，重新触发这个错误，再看看日志。
